name: pos_payment_terminal
description: POS Terminal Communication Module A comprehensive library for interfacing with POS terminals, enabling seamless communication for payment processing and other business operations.
version: 1.0.3
repository: https://github.com/KonstInt/ttk_dart

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
