name: pos_payment_terminal
description: POS Terminal Communication Module
version: 1.0.0
repository: https://github.com/KonstInt/ttk_dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  logger: ^2.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
