name: pos_payment_terminal
description: POS Terminal Communication Module A comprehensive library for interfacing with Point-of-Sale (POS) terminals, enabling seamless communication for payment processing and other business operations. Supports various POS terminal protocols, providing a unified interface for developers to integrate terminal functionality into their applications.
version: 1.0.1
repository: https://github.com/KonstInt/ttk_dart

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
